platform :ios, '6.0'
pod 'MMDrawerController', '~>0.5.1'
pod 'Reachability',  '~> 3.0.0'
pod 'CocoaLumberjack',  '~> 1.7.0'
pod 'HTProgressHUD', '~> 0.1.1'
pod 'AFNetworking', '~> 2.0.3'
pod 'TSMessages',       '~> 0.9.4'
pod 'FMMoveTableView',  '~>1.1.2'
pod 'SVPullToRefresh',	'~>0.4.1'
pod 'FXLabel',       '~> 1.5'
